# Site settings
title: Wijnand Baretta
email: wijnandb@retta.nl
description: > # this means to ignore newlines until "baseurl:"
  .....
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wijnandb.github.io/" # the base hostname & protocol for your site
twitter_username: wijnandb
github_username:  wijnandb
facebook: wijnandb
linkedin: wijnandbaretta
google_plus: WijnandBaretta
name: Wijnand Baretta

# Build settings
markdown: kramdown
